// src/Painter.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { effects, getDefaults, type Effect } from "./effects/index";
  import Magnifier from "./Magnifier.svelte";

  const DEFAULT_IMAGE =
    "https://images.pexels.com/photos/17619209/pexels-photo-17619209/free-photo-of-light-road-traffic-vacation.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2";

  let selectedEffect: Effect = $state(effects[0]);
  let params: Record<string, number> = $state(getDefaults(effects[0]));

  let originalCanvas = $state<HTMLCanvasElement>(undefined!);
  let processedCanvas = $state<HTMLCanvasElement>(undefined!);

  function selectEffect(effect: Effect) {
    selectedEffect = effect;
    params = getDefaults(effect);
  }

  function drawImageByUrl(url: string) {
    const img = new Image();
    img.crossOrigin = "Anonymous";
    img.addEventListener("load", function () {
      originalCanvas.width = this.width;
      originalCanvas.height = this.height;
      originalCanvas.getContext("2d")!.drawImage(this, 0, 0);
    });
    img.src = url;
  }

  function handleFileUpload(e: Event) {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.addEventListener("load", () => {
      drawImageByUrl(reader.result as string);
    });
    reader.readAsDataURL(file);
  }

  function handleApply() {
    selectedEffect.apply(originalCanvas, processedCanvas, params);
  }

  onMount(() => {
    drawImageByUrl(DEFAULT_IMAGE);
  });
</script>

<div class="panels">
  <section class="panel">
    <h2>Original</h2>
    <div class="canvas-wrap">
      <Magnifier canvas={originalCanvas}>
        <canvas bind:this={originalCanvas}></canvas>
      </Magnifier>
    </div>

    <div class="controls">
      <label class="file-upload">
        <span class="file-upload-label">Choose image</span>
        <input type="file" accept="image/*" onchange={handleFileUpload} />
      </label>

      <div class="effect-selector">
        {#each effects as effect (effect.id)}
          <button
            class="effect-btn"
            class:active={selectedEffect.id === effect.id}
            onclick={() => selectEffect(effect)}
          >
            {effect.name}
          </button>
        {/each}
      </div>

      {#if selectedEffect.params.length > 0}
        <div class="params">
          {#each selectedEffect.params as paramDef (paramDef.name)}
            <label class="param">
              <span>{paramDef.label}</span>
              <input
                type="number"
                min={paramDef.min}
                max={paramDef.max}
                value={params[paramDef.name]}
                oninput={(e) => {
                  params[paramDef.name] = Number((e.target as HTMLInputElement).value);
                }}
              />
            </label>
          {/each}
        </div>
      {/if}

      <button class="apply-btn" onclick={handleApply}>
        Apply Effect
      </button>
    </div>
  </section>

  <section class="panel">
    <h2>Result</h2>
    <div class="canvas-wrap">
      <Magnifier canvas={processedCanvas}>
        <canvas bind:this={processedCanvas}></canvas>
      </Magnifier>
    </div>
  </section>
</div>

<style>
  .panels {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 2rem;
    align-items: start;
  }

  @media (max-width: 800px) {
    .panels {
      grid-template-columns: 1fr;
    }
  }

  .panel {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 1.5rem;
  }

  h2 {
    font-family: "Playfair Display", Georgia, serif;
    font-size: 1.15rem;
    font-weight: 400;
    color: var(--text-muted);
    margin-bottom: 1rem;
  }

  .canvas-wrap {
    position: relative;
    background: var(--canvas-bg);
    border-radius: 6px;
    overflow: hidden;
    line-height: 0;
  }

  .canvas-wrap canvas {
    width: 100%;
    height: auto;
    display: block;
  }

  .controls {
    margin-top: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .file-upload {
    position: relative;
    cursor: pointer;
  }

  .file-upload input {
    position: absolute;
    inset: 0;
    opacity: 0;
    cursor: pointer;
  }

  .file-upload-label {
    display: block;
    padding: 0.6rem 1rem;
    border: 1px dashed var(--border);
    border-radius: 6px;
    color: var(--text-muted);
    font-size: 0.85rem;
    text-align: center;
    transition: border-color 0.2s, color 0.2s;
  }

  .file-upload:hover .file-upload-label {
    border-color: var(--accent);
    color: var(--text);
  }

  .effect-selector {
    display: flex;
    flex-wrap: wrap;
    gap: 0.4rem;
  }

  .effect-btn {
    padding: 0.4rem 0.75rem;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 6px;
    color: var(--text-muted);
    font-family: inherit;
    font-size: 0.8rem;
    cursor: pointer;
    transition: border-color 0.2s, color 0.2s, background 0.2s;
  }

  .effect-btn:hover {
    border-color: var(--accent);
    color: var(--text);
  }

  .effect-btn.active {
    background: var(--accent);
    border-color: var(--accent);
    color: var(--bg);
  }

  .params {
    display: flex;
    gap: 0.75rem;
  }

  .param {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }

  .param span {
    font-size: 0.75rem;
    color: var(--text-muted);
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .param input {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 0.5rem 0.7rem;
    color: var(--text);
    font-size: 0.9rem;
    font-family: inherit;
    width: 100%;
    transition: border-color 0.2s;
  }

  .param input:focus {
    outline: none;
    border-color: var(--accent);
  }

  .apply-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.7rem 1.5rem;
    background: var(--accent);
    color: var(--bg);
    border: none;
    border-radius: 6px;
    font-family: inherit;
    font-size: 0.9rem;
    font-weight: 500;
    cursor: pointer;
    transition: background 0.2s;
  }

  .apply-btn:hover {
    background: var(--accent-hover);
  }
</style>

// src/src/painter.tsx
import {useEffect, useRef, useState} from "preact/compat";

const Painter = () => {
    const [intensity, setIntensity] = useState(25);
    const [radius, setRadius] = useState(4);
    const [processing, setProcessing] = useState(false);

    const originalImage = useRef<HTMLCanvasElement>()
    const processedImage = useRef<HTMLCanvasElement>()

    const drawImageByUrl = (url) => {
        const img = new Image()

        img.addEventListener('load', function () {
            originalImage.current.width = (this.width); // /2
            originalImage.current.height = (this.height); // /2

            const originalImageCtx = originalImage.current.getContext("2d")
            originalImageCtx.drawImage(this, 0, 0, originalImage.current.width, originalImage.current.height);
        });

        img.crossOrigin = "Anonymous"
        img.src = url
    }

    const uploadLocalImage = (imageFile) => {
        const reader = new FileReader();

        reader.addEventListener('load', () => {
            drawImageByUrl(reader.result)
        })

        reader.readAsDataURL(imageFile);
    }

    const applyOilEffect = () => {
        // inspired by https://codepen.io/loktar00/pen/Rwgxor

        const originalImageCtx = originalImage.current.getContext("2d")
        const processedImageCtx = processedImage.current.getContext("2d")

        setProcessing(true);

        const width = originalImage.current.width,
            height = originalImage.current.height,
            imgData = originalImageCtx.getImageData(0, 0, width, height),
            pixData = imgData.data;

        processedImage.current.width = width;
        processedImage.current.height = height;

        const destImageData = processedImageCtx.createImageData(width, height),
            destPixData = destImageData.data,
            intensityLUT = [],
            rgbLUT = [];

        for (var y = 0; y < height; y++) {
            intensityLUT[y] = [];
            rgbLUT[y] = [];

            for (var x = 0; x < width; x++) {
                var idx = (y * width + x) * 4,
                    r = pixData[idx],
                    g = pixData[idx + 1],
                    b = pixData[idx + 2],
                    avg = (r + g + b) / 3;

                intensityLUT[y][x] = Math.round((avg * intensity) / 255);

                rgbLUT[y][x] = {
                    r: r,
                    g: g,
                    b: b
                };
            }
        }

        for (y = 0; y < height; y++) {
            for (x = 0; x < width; x++) {
                const pixelIntensityCount = [];

                // Find intensities of nearest pixels within radius.
                for (var yy = -radius; yy <= radius; yy++) {
                    for (var xx = -radius; xx <= radius; xx++) {
                        if (y + yy > 0 && y + yy < height && x + xx > 0 && x + xx < width) {
                            const intensityVal = intensityLUT[y + yy][x + xx];

                            if (!pixelIntensityCount[intensityVal]) {
                                pixelIntensityCount[intensityVal] = {
                                    val: 1,
                                    r: rgbLUT[y + yy][x + xx].r,
                                    g: rgbLUT[y + yy][x + xx].g,
                                    b: rgbLUT[y + yy][x + xx].b
                                }
                            } else {
                                pixelIntensityCount[intensityVal].val++;
                                pixelIntensityCount[intensityVal].r += rgbLUT[y + yy][x + xx].r;
                                pixelIntensityCount[intensityVal].g += rgbLUT[y + yy][x + xx].g;
                                pixelIntensityCount[intensityVal].b += rgbLUT[y + yy][x + xx].b;
                            }
                        }
                    }
                }

                pixelIntensityCount.sort( (a, b) => {
                    return b.val - a.val;
                });

                const curMax = pixelIntensityCount[0].val, dIdx = (y * width + x) * 4;

                destPixData[dIdx] = ~~ (pixelIntensityCount[0].r / curMax);
                destPixData[dIdx + 1] = ~~ (pixelIntensityCount[0].g / curMax);
                destPixData[dIdx + 2] = ~~ (pixelIntensityCount[0].b / curMax);
                destPixData[dIdx + 3] = 255;
            }
        }

        // change this to ctx to instead put the data on the original canvas
        processedImageCtx.putImageData(destImageData, 0, 0);

        setProcessing(false);
    }

    useEffect(() => {
        drawImageByUrl("https://images.pexels.com/photos/17619209/pexels-photo-17619209/free-photo-of-light-road-traffic-vacation.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2")
    }, [])

    return (
        <>
            <div>
                <h2>Original</h2>
                <canvas ref={originalImage} id="original-image"></canvas>
                <div className="uploader">
                    <input type="file" accept ="image/*" onChange={(event) => uploadLocalImage(event.target.files[0])}/>
                </div>
                <div className="params">
                    <input type="number" name="intensity" value={intensity} onChange={(event) => setIntensity(event.target.value)} />
                    <input type="number" name="radius" value={radius} onChange={(event) => setRadius(event.target.value)} />
                    <button onClick={() => applyOilEffect()}>Apply</button>
                </div>
            </div>
            <div>
                <h2>Oil Painting Effect {processing && <span>(processing..)</span>}</h2>
                <div>
                    {processing && <span className="loader"></span>}
                    <canvas ref={processedImage} id="processed-image"></canvas>
                </div>
            </div>
        </>
    )
}

export default Painter;
